### ISSUE TITLE
Fill out remaining episodes data

### ISSUE THREAD

**Issue by sbddesign** [ConorOkus/bitcoindevelopers.xyz#6]
Populate `./episodes` with remaining episodes

**Comment by sbddesign** [comment]
Added all the episodes as markdown files in the episodes dir. @ConorOkus do we have show notes for these from the old site?

**Comment by ConorOkus** [comment]
Basically, they are the same as what is in the Youtube descriptions. Thanks!

**Comment by sbddesign** [comment]
Ok, I pulled in the descriptions and links f rom YouTube.
